catcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #Root paths in Django are represented with an empty string '' instead of '/'.
    #includes requires a string:
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cats/', views.cats_index, name='index'),
    path('cats/<int:cat_id>/', views.cats_detail, name='detail'),
    path('cats/create/', views.CatCreate.as_view(), name='cats_create'),
    path('cats/<int:pk>/update/', views.CatUpdate.as_view(), name='cats_update'),
    path('cats/<int:pk>/delete/', views.CatDelete.as_view(), name='cats_delete'),
    path('cats/<int:cat_id>/add_feeding/', views.add_feeding, name='add_feeding')
]
# pk stands for primary key

main_app/models.py
from django.db import models
from django.urls import reverse

class Cat(models.Model):
  name = models.CharField(max_length=100)
  breed = models.CharField(max_length=100)
  description = models.TextField(max_length=350)
  age = models.IntegerField()

  def __str__(self):
    return self.name
    
  def get_absolute_url(self):
    return reverse('detail', kwargs={'cat_id': self.id})
    # Instance method, take reference to the instance
  
class Feeding(models.Model):
  MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
  )
  date = models.DateField('feeding date')
  meal = models.CharField(max_length=1, choices=MEALS)
  cat = models.ForeignKey(Cat, on_delete=models.CASCADE)
  # takes the model its referencing and an on_delete argument
  # CASCADE will delete all the feedings if a cat is deleted

  def __str__(self):
    return f'{self.get_meal_display()} on {self.date}'
  # get_xyz_display will return the values with the keys from our MEALS tuples
  # used on fields that contain choices

  class Meta:
    ordering = ('-date',)

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ('date', 'meal')

main_app/views.py
from django.shortcuts import render, redirect
from .models import Cat
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import FeedingForm

# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def cats_index(request):
    cats = Cat.objects.all()
    # all gives us all related data
    return render(request, 'cats/index.html', {
        'cats': cats
    })

def cats_detail(request, cat_id):
    cat = Cat.objects.get(id=cat_id)
    feeding_form = FeedingForm()
    return render(request, 'cats/detail.html', {
        'cat': cat,
        'feeding_form': feeding_form
    })

def add_feeding(request, cat_id):
    # access form field input values
    submitted_form = FeedingForm(request.POST) # this creates django's version of req.body
    # validate form input
    if submitted_form.is_valid():
        # if form input is valid, we'll save an in-memory copy of the new feeding object
        new_feeding = submitted_form.save(commit=False)
        # attach the cat id to the in-memory object
        new_feeding.cat_id = cat_id
        # save completed feeding object in the database
        new_feeding.save()
        # redirect back to the cat detail page
    return redirect('detail', cat_id=cat_id)

class CatCreate(CreateView):
    model = Cat
    fields = '__all__'
    # When the template is rendered for this view it will need to know which fields to add. 
    # This says "when you create this template, add all views"

class CatUpdate(UpdateView):
    model = Cat
    fields = ('name', 'description', 'age')
    # using a tuple for more security and better performance?

class CatDelete(DeleteView):
    model = Cat
    success_url = '/cats/'
    

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>About Us:</h1>
<h5>We like Cats!</h5>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Cat Collector</title>
  <link rel="stylesheet" href="{% static 'css/style.css'%}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="black nav-wrapper">
        <ul>
          <li><a href="{% url 'home'%}" class="left brand-logo">&nbsp;&nbsp;Cat Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about'%}">About</a></li>
          <li><a href="{% url 'cats_create' %}">Add a Cat</a></li>
          <li><a href="{% url 'index'%}">View All My Cats</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="black page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Cat Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/cats/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Cat List</h1>

<div class="row">
  <div class="col s6 m6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ cat.name }}</span>
        <p>Breed: {{ cat.breed }}</p>
        <p>Description: {{ cat.description }}</p>
        {% if cat.age > 0 %}
          <p>Age: {{ cat.age }}</p>
        {% else %}
          <p>Age: Kitten</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'cats_update' cat.id %}">Update</a>
        <a href="{% url 'cats_delete' cat.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6 m6">
    <form action="{% url 'add_feeding' cat.id %}" method="POST">
      {% csrf_token %}
      {{ feeding_form.as_p }}
      <input type="submit" value="Add Feeding" class=" btn blue">
    </form>
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Meal</th>
        </tr>
      </thead>
      <tbody>
        {% for feeding in cat.feeding_set.all%}
        <tr>
          <td>{{ feeding.date }}</td>
          <td>{{ feeding.get_meal_display }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<script>
  const dateEl = document.getElementById('id_date')
  const selectEl = document.getElementById('id_meal')

  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true
  })

  M.FormSelect.init(selectEl)

</script>

{% endblock %}

main_app/templates/cats/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Cat List</h1>

{% for cat in cats %}
<a href="/cats/{{ cat.id }}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ cat.name }}</span>
      <p>Breed: {{ cat.breed }}</p>
      <p>Description: {{ cat.description }}</p>
      {% if cat.age > 0 %}
        <p>Age: {{ cat.age }}</p>
      {% else %}
        <p>Age: Kitten</p>
      {% endif %}
    </div>
  </div>
</a>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Welcome to Cat Collector</h1>
{% endblock %}

main_app/templates/main_app/cat_confirm_delete.html
{% extends "base.html" %}
{% block content %}

<h2>Are you sure you want to delete {{ object.name }}</h2>

<form action="" method="POST">
    {% csrf_token %}
    <input value="Yes, I want to delete {{ object.name }}" type="submit" class="btn red">
    <a class="btn blue" href="{% url 'detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/cat_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
  <h1>Update {{ object.name }}'s Details</h1>
{% else %}
<h1>Create Cat</h1>
{% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
  </form>

{% endblock %}